### ISSUE TITLE
package manager release?

### ISSUE THREAD

**Issue by bubenkoff** [AndyHitchman/sublime-gherkin-auto-complete#2]
Please register this as a package for sublime so we can install it via sublime package manager

**Comment by bubenkoff** [comment]
added PR myself https://github.com/wbond/package_control_channel/pull/3989

**Comment by FichteFoll** [comment]
@bubenkoff, you need to rebase onto current `master`.

@AndyHitchman, please acknowledge this addition.

**Comment by AndyHitchman** [comment]
See comment on your pull request. Tried this but got a rejection. Hope you get it through.

**Comment by bubenkoff** [comment]
https://github.com/wbond/package_control_channel/pull/3989
they only asked about your approval, no objections yet
please approve it explicitly there

**Comment by bubenkoff** [comment]
i've checked the cucumber bundle and i can't say i like it's idea

**Comment by bubenkoff** [comment]
but in the end i just want it (autocompletion) to work
if you think that it's better to merge this plugin into that bundle - i'll do that with np

**Comment by AndyHitchman** [comment]
I don't mind which way it goes. I never got the bundle to work properly.

**Comment by AndyHitchman** [comment]
Closing as pull request on package control accepted. Nice job @bubenkoff.
